### ISSUE TITLE
regal fix failed to establish git repo: failed to check .git directory

### ISSUE THREAD

**Issue by grosser** [StyraInc/regal#1281] opened 2024-12-01 19:33 UTC
```
regal fix policies/capabilitiesdropall/src.rego
failed to establish git repo: failed to check .git directory: stat policies/capabilitiesdropall/src.rego/.git: not a directory
```

need some option to set the git root or ideally not  need git at all

v0.29.2

**Comment by anderseknert** [comment] 2024-12-01 20:11
Hi @grosser! And thanks for reporting that. Does the `--force` option help alleviate this? It's basically there to allow side-stepping the git requirement, but could be that this stat check is done before that, and if so, that should be fixed. If not, it'd be good to include a pointer to `--force` in the error message.

Perhaps we were a little overly cautious about `regal fix`, but the idea was that we wanted to ensure that users could easily revert any changes made by the command. And rather than having to implement "undo" from scratch, requiring a git repo in a clean state seemed like a good first option.

**Comment by anderseknert** [comment] 2024-12-01 22:58
We're not messing with anyone's git state — it's a check to ensure the user has a chance to revert a potentially disruptive change themselves. We don't modify anything through git.

This check was added with the [directory-package-mismatch](https://docs.styra.com/regal/rules/idiomatic/directory-package-mismatch) rule, which doesn't just change files where they're found (like the formatters you mention) but move files and directories around to match the package path of the Rego modules.

I don't think we'll be changing the default for that in the near future, but obviously the `--force` flag should bypass that entirely, and clearly it doesn't. Looks like it's not taken into account [here](https://github.com/StyraInc/regal/blob/main/cmd/fix.go#L348). I'll fix that tomorrow.

**Comment by grosser** [comment] 2024-12-01 23:12
Thx for taking a look 👍 

I'm running with `--disable directory-package-mismatch`, so it should not check anything.

The error should say something about either using --force or disabling directory-package-mismatch (if that is fixed to no longer need the git check).

**Comment by anderseknert** [comment] 2024-12-01 23:24
Agreed! Any error caused by that check should point out the `--force` option for anyone who doesn't care about it. Disabling the git check when `directory-package-mismatch` is disabled doesn't sound like a terrible idea either.. I'll think about it.

The whole `fix` command is pretty new and nowhere near as battle-tested as the linter... so as I said — perhaps we were overly cautious here and can adjust the defaults later. But let's first at least make sure `--force` works as we intended :)

**Closed** 2024-12-03 09:48 UTC
